hologram:
  location:
    x: 0.5
    y: 2
    z: 0.5
  lines:
    - '[regionName]'
    - '&fВладелец: {S}[owner]'
    - '&fЗащита: {S}%sg_health![rgName]%'

mysql:
  url: 'jdbc:mysql://localhost:3306/telegram'
  username: 'root'
  password: 'Ufus@2008'
  driverClass: 'com.mysql.cj.jdbc.Driver'
  tableName: 'SateGuard'
  poolSize: 10
  maxRetries: 5
  asyncThreadPoolSize: 10

settings:
  maximumStorages: 64

  night:
    title: '{S}Судная ночь | [lifeTime]'
    barStyle: 'SEGMENTED_10'
    barColor: 'PURPLE'
    endIn: 21600 # Секунды
    shards:
      1-50: '2-3'
      51-100: '4-6'
regions:
  smallPrivate:
    material: DIAMOND_BLOCK
    radius: 5
    health: 20
    maxLevel: 20
    displayName: '{S}Малый регион'
    lore:
      - ''
      - '&fРазмер региона: {M}10х10'
      - ''
  mediumPrivate:
    material: DIAMOND_ORE
    radius: 7
    health: 20
    displayName: '{S}Средний регион'
    lore:
      - ''
      - '&fРазмер региона: {M}15х15'
      - ''
  largePrivate:
    material: ANCIENT_DEBRIS
    radius: 12
    health: 30
    displayName: '{S}Большой регион'
    lore:
      - ''
      - '&fРазмер региона: {M}25х25'
      - ''
  enormousPrivate:
    material: NETHERITE_BLOCK
    radius: 22
    health: 40
    displayName: '{S}Космический регион'
    lore:
      - ''
      - '&fРазмер региона: {M}45х45'
      - ''

levelTypes:
  OPENED:
    material: LIME_STAINED_GLASS_PANE
    enchanted: true
    localName: 'Открыт'
  NEXT:
    material: YELLOW_STAINED_GLASS_PANE
    enchanted: false
    localName: 'Следующий'
  CLOSED:
    material: RED_STAINED_GLASS_PANE
    enchanted: false
    localName: 'Недоступен'


messages:
  reloaded: '{S}Плагин перезагружен!'
  noSuchPlayer: '{E}Игрока с ником [name] не существует!'
  regionCreated: '{S}Установлен [regionName]'
  regionRemoved: '{S}Удален [regionName]'
  flagRegistered: '{S}Флаг {M}[flag] {S}успешно зарегистрирован!'
  flagAlreadyRegistered: '{S}Флаг {M}[flag] {S}уже существует!'
  onEnter: '{S}Вы вторглись на территорию игрока {M}[player]'
  onExit: '{S}Вы покинули на территорию игрока {M}[player]'
  giveShard: '{S}Выдано [amount] осколков региона'
  maxShards: '{E}Нельзя положить больше [amount] осколков!'
  intersected: '{E}Нельзя установить регион, поскольку он будет пересекаться с другим!'
  DBnewAttempt: '{E}Ошибка при исполнении запроса [query], попытка [attempt]'
  DBbadConnection: '{E}Была устранена ошибка битого соединения!'
  outOfRegion: '{E}Войдите в регион!'
  level:
    openedLevel: '{E}Этот уровень уже открыт!'
    lowBalance: '{E}Недостаточно монет на балансе!'
    lowShards: '{E}Недостаточно осколков!'
  DBError: '{E}Произошла ошибка сохранения данных, обратитесь в техническую поддержку с этой проблемой, решим в кратчайшие сроки'
  event:
    alreadyStarted: '{E}Ивент уже запущен!'
    started: '{S}Ивент судной ночи начался!'
    eventNotActive: '{E}Ивент еще не запущен!'
    stopped: '{S}Ивент завершен!'
    nightStarted:
      title: '{S}Судная ночь'
      subTitle: '{M}Регионы потеряли прочность...'
      broadcast:
        - '{S}Судная ночь началась!'
        - '{S}Ваш регион может быть уязвим!'
        - ''
        - '&7&oДа прибудет анархия...'
    nightEnded:
      title: '{S}Судная ночь'
      subTitle: '{M}Регионы вновь неприкасаемы'
      broadcast:
        - '{S}Судная ночь завершилась!'
        - '{S}Каждый регион, который пережил судную ночь получил осколки!'
        - ''
        - '&7&oКак тут тихо...'

  commands:
    info:
      - '{S}⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶{M}[regionName]{S}⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶⊶'
      - '{S}Владелец: {M}[owner]'
      - '{S}Участники: {M}[members]'
      - '{S}Границы: {M}[border1] {S}- {M}[border2]'
      - ''
    newMember: '{S}Игрок {M}[player] {S}теперь является участником этого региона!'
    alreadyMember: '{S}Игрок {M}[player] {S}уже является участником этого региона!'
    notMember: '{S}Участника с ником {M}[player] {S}в этом регионе нет!'
    removedMember: '{S}Участник {M}[player] {S}удален из этого региона!'
    noMembers: '{S}Отсутствуют'